import type { Metadata } from "next";
import "@/styles/globals.css";
import HeroSection from "@/Components/AboutPage/HeroSection";

export const metadata: Metadata = {
  title: "WooHealth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <HeroSection/>
          {children}
      </body>
    </html>
  );
}
