import type { Metadata } from "next";
import "@/styles/globals.css";


export const metadata: Metadata = {
  title: "WooHealth",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  active,
  claimsSummary,
  dependant,
  learn,
  medical,
  payment,
  upcoming,
  wallet,
  welcome,
}: Readonly<{
  children: React.ReactNode;
  active: React.ReactNode;
  claimsSummary: React.ReactNode;
  dependant: React.ReactNode;
  learn: React.ReactNode;
  medical: React.ReactNode;
  payment: React.ReactNode;
  upcoming: React.ReactNode;
  wallet: React.ReactNode;
  welcome: React.ReactNode;
}>) {
  return (
    <div className="container w-full bg-[#FAFAFA]">
      <div>{welcome}</div>
      <div className="grid grid-cols-4 px-4">
        <div>{active}</div>
        <div>{wallet}</div>
        <div>{dependant}</div>
        <div>{learn}</div>
      </div>
      <div className="px-4">{children}</div>
      <div className="px-4 flex gap-10">
        <div className="w-[60%]">
          <div>{claimsSummary}</div>
          <div>{medical}</div>
        </div>
        <div className="">
          <div>{payment}</div>
          <div>{upcoming}</div>
        </div>
      </div>
    </div>
  );
}
