import type { Metadata } from "next";
import "@/styles/globals.css";
import active from './@active'
import claimS


export const metadata: Metadata = {
  title: "WooHealth",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  active,
  claimsSummary,
  dependant,
  learn,
  medical,
  payment,
  upcoming,
  wallet,
  welcome,
}: Readonly<{
  children: React.ReactNode;
  active: React.ReactNode;
  claimsSummary: React.ReactNode;
  dependant: React.ReactNode;
  learn: React.ReactNode;
  medical: React.ReactNode;
  payment: React.ReactNode;
  upcoming: React.ReactNode;
  wallet: React.ReactNode;
  welcome: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
