export interface User {
  email: string;
  password: string;
  phone: string;
  firstName: string;
  lastName: string;
  userId: string;
  role: string;
  specialization: string;
  availability: boolean;
  plan: string | null;
  latitude: string;
  longitude: string;
  profile_pic: string;
  businessId: string | null;
  status: string | null;
  department: string | null;
  dateOfBirth: string | null;
  gender: string | null;
  enrolleeNumber: string | null;
  policyNumber: string | null;
  otherNames: string | null;
  relationship: string | null;
  providerCode: string | null;
  providerName: string | null;
  providerState: string | null;
  preExistingCond: string | null;
  passportUrl: string | null;
  nakasoft_id: string | null;
  source: string | null;
  fcmToken: string | null;
  $id: string;
  $sequence: number;
  $createdAt: string;
  $updatedAt: string;
  $permissions: string[];
  $databaseId: string;
  $collectionId: string;
}
