import type { Metadata } from "next";
import "@/styles/globals.css";


export const metadata: Metadata = {
  title: "WooHealth",
  description: "Generated by create next app",
};

export default function FundWalletLayout({
  header,
  search,
  stats,
  upcoming,
}: Readonly<{
  header: React.ReactNode;
  search: React.ReactNode;
  stats: React.ReactNode;
  upcoming: React.ReactNode;
}>) {
  return (
    <>
    <div className="w-full">
      <div className="sticky top-0">{header}</div>
      <div className="p-4 w-full">
        <div className="flex gap-6">
            <div className="w-[65%]">{upcoming}</div>
            <div className="" style={{width: '35%'}}>{stats}</div>
        </div>
        <div className="">{search}</div>
      </div>
    </div>
    </>
  );
}