import type { Metadata } from "next";
import "@/styles/globals.css";
import NavBar from "@/Components/NavBar";
import SmallFooter from "@/Components/SmallFooter";
import { AuthProvider } from "@/context/Authcontext";


export const metadata: Metadata = {
  title: "WooHealth",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavBar />
        <AuthProvider>
          {children}
        </AuthProvider>
        <SmallFooter />
      </body>
    </html>
  );
}
