import type { Metadata } from "next";
import "@/styles/globals.css";
import SideBar from "@/Components/SideBar";


export const metadata: Metadata = {
  title: "WooHealth",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex gap-6`}
      >
        <SideBar />
        {children}
      </body>
    </html>
  );
}
